name: edulink_flutter
description: A new Flutter project for EduLink app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  intl: ^0.19.0
  provider: ^6.1.1 # Simple state management
  fl_chart: ^0.66.0
  firebase_core: ^3.4.0
  firebase_auth: ^5.1.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.1.2
  font_awesome_flutter: ^10.7.0
  http: ^1.2.0
  pdf: ^3.10.8
  printing: ^5.12.0
  video_player: ^2.8.2
  flutter_animate: ^4.5.0
  csv: ^6.0.0
  file_picker: ^8.0.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
